# Generated by Django 4.1.4 on 2022-12-24 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_author', models.CharField(blank=True, max_length=100, null=True)),
                ('second_author', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
