# Generated by Django 4.1.4 on 2022-12-27 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_delete_author_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rubric',
            options={'ordering': ['name'], 'verbose_name': 'Rubric', 'verbose_name_plural': 'Rubrics'},
        ),
    ]
